// Mock project data for ExplorePage
export const mockProjects = [
  {
    id: 1,
    title: 'AI 챗봇 자동 응답 시스템',
    description: '고객 문의 자동 처리를 위한 AI 기반 챗봇 시스템. GPT-4를 활용한 자연어 처리 및 사내 FAQ 학습 기능 포함',
    author: '김지현',
    department: 'IT기획팀',
    tags: ['Python', 'AI/ML', 'ChatGPT', 'FastAPI'],
    stars: 127,
    forks: 34,
    updatedAt: '2시간 전',
  },
  {
    id: 2,
    title: '엑셀 데이터 자동화 스크립트',
    description: '반복적인 엑셀 작업을 자동화하는 Python 스크립트 모음. 데이터 정제, 분석, 리포트 생성 자동화',
    author: '이동훈',
    department: '재무팀',
    tags: ['Python', 'RPA', 'Excel', 'Pandas'],
    stars: 98,
    forks: 45,
    updatedAt: '5시간 전',
  },
  {
    id: 3,
    title: 'React 디자인 시스템',
    description: '사내 웹 서비스를 위한 통합 디자인 시스템. 재사용 가능한 UI 컴포넌트 라이브러리',
    author: '박서연',
    department: '프론트엔드팀',
    tags: ['React', 'TypeScript', 'Tailwind CSS', 'Storybook'],
    stars: 156,
    forks: 28,
    updatedAt: '1일 전',
  },
  {
    id: 4,
    title: 'API 모니터링 대시보드',
    description: '실시간 API 성능 모니터링 및 장애 알림 시스템. Grafana 기반 커스텀 대시보드',
    author: '최민수',
    department: '백엔드팀',
    tags: ['Node.js', 'Grafana', 'Monitoring', 'Docker'],
    stars: 82,
    forks: 19,
    updatedAt: '2일 전',
  },
  {
    id: 5,
    title: 'Slack 봇 알림 자동화',
    description: '프로젝트 진행 상황을 Slack으로 자동 알림해주는 봇. Jira, GitHub 통합',
    author: '정수아',
    department: 'DevOps팀',
    tags: ['Node.js', 'Slack API', 'Automation'],
    stars: 45,
    forks: 12,
    updatedAt: '30분 전',
  },
  {
    id: 6,
    title: '보안 취약점 스캐너',
    description: 'AWS 리소스의 보안 취약점을 자동으로 스캔하고 리포트를 생성하는 도구',
    author: '강태호',
    department: '보안팀',
    tags: ['Python', 'AWS', 'Security', 'CLI'],
    stars: 67,
    forks: 15,
    updatedAt: '1시간 전',
  },
  {
    id: 7,
    title: 'Spring Boot REST API 템플릿',
    description: '사내 표준 Spring Boot 프로젝트 템플릿. JWT 인증, 로깅, 예외 처리 포함',
    author: '이민준',
    department: '백엔드팀',
    tags: ['Java', 'Spring', 'REST API', 'JWT'],
    stars: 73,
    forks: 29,
    updatedAt: '3일 전',
  },
  {
    id: 8,
    title: 'Docker 배포 자동화 스크립트',
    description: 'Docker 컨테이너 빌드 및 배포를 자동화하는 Shell 스크립트 모음',
    author: '김민석',
    department: 'DevOps팀',
    tags: ['Docker', 'Shell', 'CI/CD', 'Automation'],
    stars: 54,
    forks: 18,
    updatedAt: '1주일 전',
  },
]

export const ITEMS_PER_PAGE = 6
export const MAX_VISIBLE_PAGES = 5
