import type { AchievementDefinition } from './achievements-types'

export const ALL_ACHIEVEMENTS: AchievementDefinition[] = [
  // ========================================
  // 탐색 관련 (Exploration)
  // ========================================
  // 프로젝트 조회
  {
    id: 'first_view',
    title: '첫 발걸음',
    description: '첫 프로젝트를 조회했습니다',
    icon: '👣',
    category: 'exploration',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'explorer_10',
    title: '탐험가',
    description: '10개 프로젝트를 조회했습니다',
    icon: '🗺️',
    category: 'exploration',
    rarity: 'common',
    max: 10,
    tier: 1,
  },
  {
    id: 'explorer_25',
    title: '호기심 많은 여행자',
    description: '25개 프로젝트를 조회했습니다',
    icon: '🧭',
    category: 'exploration',
    rarity: 'common',
    max: 25,
    tier: 2,
  },
  {
    id: 'explorer_50',
    title: '진정한 탐험가',
    description: '50개 프로젝트를 조회했습니다',
    icon: '🏔️',
    category: 'exploration',
    rarity: 'rare',
    max: 50,
    tier: 3,
  },
  {
    id: 'explorer_100',
    title: '마스터 탐험가',
    description: '100개 프로젝트를 조회했습니다',
    icon: '🌋',
    category: 'exploration',
    rarity: 'epic',
    max: 100,
    tier: 4,
  },
  {
    id: 'explorer_200',
    title: '전설의 탐험가',
    description: '200개 프로젝트를 조회했습니다',
    icon: '⭐',
    category: 'exploration',
    rarity: 'legendary',
    max: 200,
    tier: 5,
  },
  {
    id: 'explorer_500',
    title: '프로젝트 수집가',
    description: '500개 프로젝트를 조회했습니다',
    icon: '💎',
    category: 'exploration',
    rarity: 'legendary',
    max: 500,
    tier: 6,
  },
  {
    id: 'explorer_1000',
    title: '탐색의 신',
    description: '1000개 프로젝트를 조회했습니다',
    icon: '🌟',
    category: 'exploration',
    rarity: 'mythic',
    max: 1000,
    tier: 7,
  },
  {
    id: 'explorer_2500',
    title: '무한 탐험가',
    description: '2500개 프로젝트를 조회했습니다',
    icon: '🔮',
    category: 'exploration',
    rarity: 'mythic',
    max: 2500,
    tier: 8,
  },
  {
    id: 'explorer_5000',
    title: '모든 것을 본 자',
    description: '5000개 프로젝트를 조회했습니다',
    icon: '👁️',
    category: 'exploration',
    rarity: 'mythic',
    max: 5000,
    tier: 9,
  },
  {
    id: 'explorer_10000',
    title: '시간의 여행자',
    description: '10000개 프로젝트를 조회했습니다',
    icon: '⏳',
    category: 'exploration',
    rarity: 'mythic',
    max: 10000,
    tier: 10,
  },

  // 카테고리별 탐색
  {
    id: 'dept_1_first',
    title: '첫 관심사',
    description: '첫 번째 카테고리의 프로젝트를 조회했습니다',
    icon: '💼',
    category: 'exploration',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'dept_5_first',
    title: '다방면 탐험가',
    description: '5개 카테고리의 프로젝트를 조회했습니다',
    icon: '🎯',
    category: 'exploration',
    rarity: 'common',
    max: 5,
    tier: 2,
  },
  {
    id: 'dept_all',
    title: '전체 탐방',
    description: '모든 카테고리의 프로젝트를 조회했습니다',
    icon: '🌐',
    category: 'exploration',
    rarity: 'epic',
    max: 8,
    tier: 4,
  },

  // ========================================
  // 참여 관련 (Engagement)
  // ========================================
  // 북마크/즐겨찾기
  {
    id: 'first_bookmark',
    title: '스크랩',
    description: '첫 프로젝트를 저장했습니다',
    icon: '⭐',
    category: 'engagement',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'collector_5',
    title: '소장가 시작',
    description: '5개 프로젝트를 저장했습니다',
    icon: '📁',
    category: 'engagement',
    rarity: 'common',
    max: 5,
    tier: 1,
  },
  {
    id: 'collector_10',
    title: '수집가',
    description: '10개 프로젝트를 저장했습니다',
    icon: '📚',
    category: 'engagement',
    rarity: 'common',
    max: 10,
    tier: 2,
  },
  {
    id: 'collector_25',
    title: '열정적 수집가',
    description: '25개 프로젝트를 저장했습니다',
    icon: '📖',
    category: 'engagement',
    rarity: 'rare',
    max: 25,
    tier: 3,
  },
  {
    id: 'collector_50',
    title: '진정한 수집가',
    description: '50개 프로젝트를 저장했습니다',
    icon: '📚',
    category: 'engagement',
    rarity: 'rare',
    max: 50,
    tier: 4,
  },
  {
    id: 'collector_100',
    title: '마스터 수집가',
    description: '100개 프로젝트를 저장했습니다',
    icon: '🏛️',
    category: 'engagement',
    rarity: 'epic',
    max: 100,
    tier: 5,
  },
  {
    id: 'collector_200',
    title: '전설의 수집가',
    description: '200개 프로젝트를 저장했습니다',
    icon: '🏺',
    category: 'engagement',
    rarity: 'legendary',
    max: 200,
    tier: 6,
  },
  {
    id: 'collector_500',
    title: '박물관 관장',
    description: '500개 프로젝트를 저장했습니다',
    icon: '🏛️',
    category: 'engagement',
    rarity: 'mythic',
    max: 500,
    tier: 7,
  },
  {
    id: 'collector_1000',
    title: '보물 창고',
    description: '1000개 프로젝트를 저장했습니다',
    icon: '💰',
    category: 'engagement',
    rarity: 'mythic',
    max: 1000,
    tier: 8,
  },

  // 댓글 작성
  {
    id: 'first_comment',
    title: '목소리',
    description: '첫 댓글을 작성했습니다',
    icon: '💬',
    category: 'engagement',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'commenter_5',
    title: '소통 시작',
    description: '5개 댓글을 작성했습니다',
    icon: '🗨️',
    category: 'engagement',
    rarity: 'common',
    max: 5,
    tier: 1,
  },
  {
    id: 'commenter_10',
    title: '활발한 참여자',
    description: '10개 댓글을 작성했습니다',
    icon: '🗣️',
    category: 'engagement',
    rarity: 'common',
    max: 10,
    tier: 2,
  },
  {
    id: 'commenter_25',
    title: '의견가',
    description: '25개 댓글을 작성했습니다',
    icon: '📝',
    category: 'engagement',
    rarity: 'rare',
    max: 25,
    tier: 3,
  },
  {
    id: 'commenter_50',
    title: '소통의 명수',
    description: '50개 댓글을 작성했습니다',
    icon: '🎤',
    category: 'engagement',
    rarity: 'rare',
    max: 50,
    tier: 4,
  },
  {
    id: 'commenter_100',
    title: '커뮤니티 스타',
    description: '100개 댓글을 작성했습니다',
    icon: '⭐',
    category: 'engagement',
    rarity: 'epic',
    max: 100,
    tier: 5,
  },
  {
    id: 'commenter_200',
    title: '소통의 전설',
    description: '200개 댓글을 작성했습니다',
    icon: '🌟',
    category: 'engagement',
    rarity: 'legendary',
    max: 200,
    tier: 6,
  },
  {
    id: 'commenter_500',
    title: '말의 대가',
    description: '500개 댓글을 작성했습니다',
    icon: '🎙️',
    category: 'engagement',
    rarity: 'mythic',
    max: 500,
    tier: 7,
  },
  {
    id: 'commenter_1000',
    title: '설득의 마법사',
    description: '1000개 댓글을 작성했습니다',
    icon: '🪄',
    category: 'engagement',
    rarity: 'mythic',
    max: 1000,
    tier: 8,
  },

  // 좋아요
  {
    id: 'first_like',
    title: '첫 좋아요',
    description: '첫 좋아요를 눌렀습니다',
    icon: '👍',
    category: 'engagement',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'liker_10',
    title: '응원단',
    description: '10개 좋아요를 눌렀습니다',
    icon: '💖',
    category: 'engagement',
    rarity: 'common',
    max: 10,
    tier: 2,
  },
  {
    id: 'liker_50',
    title: '지지자',
    description: '50개 좋아요를 눌렀습니다',
    icon: '❤️',
    category: 'engagement',
    rarity: 'rare',
    max: 50,
    tier: 3,
  },
  {
    id: 'liker_100',
    title: '최고의 팬',
    description: '100개 좋아요를 눌렀습니다',
    icon: '💕',
    category: 'engagement',
    rarity: 'epic',
    max: 100,
    tier: 4,
  },
  {
    id: 'liker_500',
    title: '사랑의 전도사',
    description: '500개 좋아요를 눌렀습니다',
    icon: '💗',
    category: 'engagement',
    rarity: 'legendary',
    max: 500,
    tier: 6,
  },
  {
    id: 'liker_1000',
    title: '사랑의 신',
    description: '1000개 좋아요를 눌렀습니다',
    icon: '💘',
    category: 'engagement',
    rarity: 'mythic',
    max: 1000,
    tier: 7,
  },

  // ========================================
  // 소셜 관련 (Social)
  // ========================================
  // 공유
  {
    id: 'first_share',
    title: '전도사',
    description: '프로젝트를 처음 공유했습니다',
    icon: '📢',
    category: 'social',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'sharer_5',
    title: '소식통',
    description: '5번 프로젝트를 공유했습니다',
    icon: '📣',
    category: 'social',
    rarity: 'common',
    max: 5,
    tier: 2,
  },
  {
    id: 'sharer_10',
    title: '홍보대사',
    description: '10번 프로젝트를 공유했습니다',
    icon: '📡',
    category: 'social',
    rarity: 'rare',
    max: 10,
    tier: 3,
  },
  {
    id: 'sharer_25',
    title: '마케터',
    description: '25번 프로젝트를 공유했습니다',
    icon: '📊',
    category: 'social',
    rarity: 'rare',
    max: 25,
    tier: 4,
  },
  {
    id: 'sharer_50',
    title: '확산의 명수',
    description: '50번 프로젝트를 공유했습니다',
    icon: '📈',
    category: 'social',
    rarity: 'epic',
    max: 50,
    tier: 5,
  },
  {
    id: 'sharer_100',
    title: '바이럴 킹',
    description: '100번 프로젝트를 공유했습니다',
    icon: '🔥',
    category: 'social',
    rarity: 'legendary',
    max: 100,
    tier: 6,
  },
  {
    id: 'sharer_250',
    title: '세상을 바꾼 자',
    description: '250번 프로젝트를 공유했습니다',
    icon: '🌍',
    category: 'social',
    rarity: 'mythic',
    max: 250,
    tier: 7,
  },

  // ========================================
  // 마일스톤 (Milestone)
  // ========================================
  // 연속 방문 (스트릭)
  {
    id: 'streak_1',
    title: '첫 방문',
    description: '처음으로 방문했습니다',
    icon: '🚪',
    category: 'milestone',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'streak_2',
    title: '이틀 연속',
    description: '2일 연속 방문했습니다',
    icon: '🔄',
    category: 'milestone',
    rarity: 'common',
    max: 2,
    tier: 1,
  },
  {
    id: 'streak_3',
    title: '3일 연속',
    description: '3일 연속 방문했습니다',
    icon: '🔥',
    category: 'milestone',
    rarity: 'common',
    max: 3,
    tier: 1,
  },
  {
    id: 'streak_5',
    title: '5일 연속',
    description: '5일 연속 방문했습니다',
    icon: '⚡',
    category: 'milestone',
    rarity: 'common',
    max: 5,
    tier: 2,
  },
  {
    id: 'streak_7',
    title: '일주일 연속',
    description: '7일 연속 방문했습니다',
    icon: '💫',
    category: 'milestone',
    rarity: 'rare',
    max: 7,
    tier: 2,
  },
  {
    id: 'streak_14',
    title: '2주 연속',
    description: '14일 연속 방문했습니다',
    icon: '🌟',
    category: 'milestone',
    rarity: 'rare',
    max: 14,
    tier: 3,
  },
  {
    id: 'streak_21',
    title: '21일의 법칙',
    description: '21일 연속 방문했습니다',
    icon: '🎯',
    category: 'milestone',
    rarity: 'epic',
    max: 21,
    tier: 4,
  },
  {
    id: 'streak_30',
    title: '한 달 연속',
    description: '30일 연속 방문했습니다',
    icon: '💎',
    category: 'milestone',
    rarity: 'epic',
    max: 30,
    tier: 4,
  },
  {
    id: 'streak_60',
    title: '두 달 연속',
    description: '60일 연속 방문했습니다',
    icon: '🏆',
    category: 'milestone',
    rarity: 'epic',
    max: 60,
    tier: 5,
  },
  {
    id: 'streak_90',
    title: '3개월 연속',
    description: '90일 연속 방문했습니다',
    icon: '👑',
    category: 'milestone',
    rarity: 'legendary',
    max: 90,
    tier: 5,
  },
  {
    id: 'streak_100',
    title: '100일의 기적',
    description: '100일 연속 방문했습니다',
    icon: '🎉',
    category: 'milestone',
    rarity: 'legendary',
    max: 100,
    tier: 6,
  },
  {
    id: 'streak_180',
    title: '반년의 헌신',
    description: '180일 연속 방문했습니다',
    icon: '💍',
    category: 'milestone',
    rarity: 'legendary',
    max: 180,
    tier: 7,
  },
  {
    id: 'streak_365',
    title: '1년의 전설',
    description: '365일 연속 방문했습니다',
    icon: '🌈',
    category: 'milestone',
    rarity: 'mythic',
    max: 365,
    tier: 8,
  },
  {
    id: 'streak_500',
    title: '500일의 신화',
    description: '500일 연속 방문했습니다',
    icon: '🔮',
    category: 'milestone',
    rarity: 'mythic',
    max: 500,
    tier: 9,
  },
  {
    id: 'streak_730',
    title: '2년의 불굴',
    description: '730일 연속 방문했습니다 (2년)',
    icon: '⚜️',
    category: 'milestone',
    rarity: 'mythic',
    max: 730,
    tier: 10,
  },
  {
    id: 'streak_1000',
    title: '1000일의 제왕',
    description: '1000일 연속 방문했습니다',
    icon: '🏅',
    category: 'milestone',
    rarity: 'mythic',
    max: 1000,
    tier: 10,
  },

  // 총 방문 일수
  {
    id: 'visited_1',
    title: '첫 걸음',
    description: '1일째 방문했습니다',
    icon: '👣',
    category: 'milestone',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'visited_7',
    title: '첫 주',
    description: '7일간 방문했습니다',
    icon: '📅',
    category: 'milestone',
    rarity: 'common',
    max: 7,
    tier: 2,
  },
  {
    id: 'visited_30',
    title: '첫 달',
    description: '30일간 방문했습니다',
    icon: '📆',
    category: 'milestone',
    rarity: 'rare',
    max: 30,
    tier: 3,
  },
  {
    id: 'visited_90',
    title: '분기 달성',
    description: '90일간 방문했습니다',
    icon: '🗓️',
    category: 'milestone',
    rarity: 'rare',
    max: 90,
    tier: 4,
  },
  {
    id: 'visited_180',
    title: '반년 회원',
    description: '180일간 방문했습니다',
    icon: '📋',
    category: 'milestone',
    rarity: 'epic',
    max: 180,
    tier: 5,
  },
  {
    id: 'visited_365',
    title: '1년 회원',
    description: '365일간 방문했습니다',
    icon: '🎊',
    category: 'milestone',
    rarity: 'epic',
    max: 365,
    tier: 6,
  },
  {
    id: 'visited_730',
    title: '2년 회원',
    description: '730일간 방문했습니다',
    icon: '🎭',
    category: 'milestone',
    rarity: 'legendary',
    max: 730,
    tier: 7,
  },
  {
    id: 'visited_1095',
    title: '3년 회원',
    description: '1095일간 방문했습니다 (3년)',
    icon: '🎨',
    category: 'milestone',
    rarity: 'legendary',
    max: 1095,
    tier: 8,
  },
  {
    id: 'visited_1825',
    title: '5년의 헌신',
    description: '1825일간 방문했습니다 (5년)',
    icon: '🖼️',
    category: 'milestone',
    rarity: 'mythic',
    max: 1825,
    tier: 9,
  },
  {
    id: 'visited_3650',
    title: '10년의 전설',
    description: '3650일간 방문했습니다 (10년)',
    icon: '🏛️',
    category: 'milestone',
    rarity: 'mythic',
    max: 3650,
    tier: 10,
  },
  {
    id: 'visited_7300',
    title: '20년의 불멸',
    description: '7300일간 방문했습니다 (20년)',
    icon: '🏰',
    category: 'milestone',
    rarity: 'mythic',
    max: 7300,
    tier: 10,
  },
  {
    id: 'visited_10950',
    title: '30년의 신화',
    description: '10950일간 방문했습니다 (30년)',
    icon: '🏯',
    category: 'milestone',
    rarity: 'mythic',
    max: 10950,
    tier: 10,
  },
  {
    id: 'visited_18250',
    title: '50년의 영원',
    description: '18250일간 방문했습니다 (50년)',
    icon: '🏜️',
    category: 'milestone',
    rarity: 'mythic',
    max: 18250,
    tier: 10,
  },
  {
    id: 'visited_36500',
    title: '100년의 초월',
    description: '36500일간 방문했습니다 (100년)',
    icon: '⭐',
    category: 'milestone',
    rarity: 'mythic',
    max: 36500,
    tier: 10,
  },

  // ========================================
  // 레벨 관련 (Level)
  // ========================================
  {
    id: 'level_5',
    title: '초보자',
    description: '레벨 5에 도달했습니다',
    icon: '🌱',
    category: 'level',
    rarity: 'common',
    max: 5,
    tier: 1,
  },
  {
    id: 'level_10',
    title: '성장 중',
    description: '레벨 10에 도달했습니다',
    icon: '🌿',
    category: 'level',
    rarity: 'common',
    max: 10,
    tier: 2,
  },
  {
    id: 'level_25',
    title: '숙련자',
    description: '레벨 25에 도달했습니다',
    icon: '🌳',
    category: 'level',
    rarity: 'rare',
    max: 25,
    tier: 3,
  },
  {
    id: 'level_50',
    title: '전문가',
    description: '레벨 50에 도달했습니다',
    icon: '🏅',
    category: 'level',
    rarity: 'rare',
    max: 50,
    tier: 4,
  },
  {
    id: 'level_75',
    title: '마스터',
    description: '레벨 75에 도달했습니다',
    icon: '🎖️',
    category: 'level',
    rarity: 'epic',
    max: 75,
    tier: 5,
  },
  {
    id: 'level_100',
    title: '그랜드마스터',
    description: '레벨 100에 도달했습니다',
    icon: '🏆',
    category: 'level',
    rarity: 'epic',
    max: 100,
    tier: 6,
  },
  {
    id: 'level_150',
    title: '전설',
    description: '레벨 150에 도달했습니다',
    icon: '⭐',
    category: 'level',
    rarity: 'legendary',
    max: 150,
    tier: 7,
  },
  {
    id: 'level_200',
    title: '초월자',
    description: '레벨 200에 도달했습니다',
    icon: '🌟',
    category: 'level',
    rarity: 'legendary',
    max: 200,
    tier: 8,
  },
  {
    id: 'level_300',
    title: '신화',
    description: '레벨 300에 도달했습니다',
    icon: '💫',
    category: 'level',
    rarity: 'mythic',
    max: 300,
    tier: 9,
  },
  {
    id: 'level_500',
    title: '최강자',
    description: '레벨 500에 도달했습니다',
    icon: '👑',
    category: 'level',
    rarity: 'mythic',
    max: 500,
    tier: 10,
  },
  {
    id: 'level_1000',
    title: '레벨의 제왕',
    description: '레벨 1000에 도달했습니다',
    icon: '🔱',
    category: 'level',
    rarity: 'mythic',
    max: 1000,
    tier: 10,
  },

  // ========================================
  // XP 관련 (Experience Points)
  // ========================================
  {
    id: 'xp_100',
    title: '첫 경험치',
    description: '100 XP를 획득했습니다',
    icon: '✨',
    category: 'xp',
    rarity: 'common',
    max: 100,
    tier: 1,
  },
  {
    id: 'xp_500',
    title: '경험치 수집가',
    description: '500 XP를 획득했습니다',
    icon: '💫',
    category: 'xp',
    rarity: 'common',
    max: 500,
    tier: 2,
  },
  {
    id: 'xp_1000',
    title: '천의 경험',
    description: '1000 XP를 획득했습니다',
    icon: '⭐',
    category: 'xp',
    rarity: 'rare',
    max: 1000,
    tier: 3,
  },
  {
    id: 'xp_5000',
    title: '경험의 대가',
    description: '5000 XP를 획득했습니다',
    icon: '🌟',
    category: 'xp',
    rarity: 'rare',
    max: 5000,
    tier: 4,
  },
  {
    id: 'xp_10000',
    title: '만인의 경험',
    description: '10000 XP를 획득했습니다',
    icon: '💎',
    category: 'xp',
    rarity: 'epic',
    max: 10000,
    tier: 5,
  },
  {
    id: 'xp_25000',
    title: 'XP의 마스터',
    description: '25000 XP를 획득했습니다',
    icon: '🏆',
    category: 'xp',
    rarity: 'epic',
    max: 25000,
    tier: 6,
  },
  {
    id: 'xp_50000',
    title: 'XP의 전설',
    description: '50000 XP를 획득했습니다',
    icon: '👑',
    category: 'xp',
    rarity: 'legendary',
    max: 50000,
    tier: 7,
  },
  {
    id: 'xp_100000',
    title: '10만의 영광',
    description: '100000 XP를 획득했습니다',
    icon: '🔥',
    category: 'xp',
    rarity: 'legendary',
    max: 100000,
    tier: 8,
  },
  {
    id: 'xp_250000',
    title: '25만의 신화',
    description: '250000 XP를 획득했습니다',
    icon: '⚡',
    category: 'xp',
    rarity: 'mythic',
    max: 250000,
    tier: 9,
  },
  {
    id: 'xp_500000',
    title: '50만의 초월',
    description: '500000 XP를 획득했습니다',
    icon: '🌈',
    category: 'xp',
    rarity: 'mythic',
    max: 500000,
    tier: 10,
  },
  {
    id: 'xp_1000000',
    title: '밀레니엄',
    description: '1000000 XP를 획득했습니다',
    icon: '🌠',
    category: 'xp',
    rarity: 'mythic',
    max: 1000000,
    tier: 10,
  },

  // ========================================
  // 퀘스트 관련 (Quest)
  // ========================================
  {
    id: 'quest_1',
    title: '첫 퀘스트',
    description: '첫 일일 퀘스트를 완료했습니다',
    icon: '📜',
    category: 'quest',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'quest_7',
    title: '일주일의 퀘스트',
    description: '7개의 일일 퀘스트를 완료했습니다',
    icon: '📋',
    category: 'quest',
    rarity: 'common',
    max: 7,
    tier: 2,
  },
  {
    id: 'quest_30',
    title: '한 달의 퀘스트',
    description: '30개의 일일 퀘스트를 완료했습니다',
    icon: '📊',
    category: 'quest',
    rarity: 'rare',
    max: 30,
    tier: 3,
  },
  {
    id: 'quest_100',
    title: '퀘스트 헌터',
    description: '100개의 일일 퀘스트를 완료했습니다',
    icon: '🎯',
    category: 'quest',
    rarity: 'rare',
    max: 100,
    tier: 4,
  },
  {
    id: 'quest_365',
    title: '퀘스트 마스터',
    description: '365개의 일일 퀘스트를 완료했습니다',
    icon: '🏅',
    category: 'quest',
    rarity: 'epic',
    max: 365,
    tier: 5,
  },
  {
    id: 'quest_500',
    title: '퀘스트 전설',
    description: '500개의 일일 퀘스트를 완료했습니다',
    icon: '🏆',
    category: 'quest',
    rarity: 'legendary',
    max: 500,
    tier: 6,
  },
  {
    id: 'quest_1000',
    title: '퀘스트의 신',
    description: '1000개의 일일 퀘스트를 완료했습니다',
    icon: '👑',
    category: 'quest',
    rarity: 'mythic',
    max: 1000,
    tier: 7,
  },

  // ========================================
  // 특별 업적 (Special)
  // ========================================
  {
    id: 'early_bird',
    title: '얼리버드',
    description: '오전 6시 이전에 접속했습니다',
    icon: '🌅',
    category: 'special',
    rarity: 'rare',
    max: 1,
    tier: 3,
  },
  {
    id: 'night_owl',
    title: '나이트올',
    description: '밤 12시 이후에 접속했습니다',
    icon: '🦉',
    category: 'special',
    rarity: 'rare',
    max: 1,
    tier: 3,
  },
  {
    id: 'weekend_warrior',
    title: '주말 전사',
    description: '주말에 접속했습니다',
    icon: '⚔️',
    category: 'special',
    rarity: 'common',
    max: 1,
    tier: 1,
  },
  {
    id: 'perfectionist',
    title: '완벽주의자',
    description: '하루에 모든 퀘스트를 완료했습니다',
    icon: '💯',
    category: 'special',
    rarity: 'rare',
    max: 1,
    tier: 4,
  },
  {
    id: 'speed_runner',
    title: '스피드 러너',
    description: '접속 후 1분 안에 퀘스트를 완료했습니다',
    icon: '⚡',
    category: 'special',
    rarity: 'epic',
    max: 1,
    tier: 5,
  },
  {
    id: 'marathon',
    title: '마라토너',
    description: '한 번의 세션에서 10개 프로젝트를 조회했습니다',
    icon: '🏃',
    category: 'special',
    rarity: 'rare',
    max: 10,
    tier: 3,
  },
  {
    id: 'dedicated_fan',
    title: '충성스러운 팬',
    description: '같은 프로젝트를 10번 조회했습니다',
    icon: '💝',
    category: 'special',
    rarity: 'rare',
    max: 10,
    tier: 4,
  },
  {
    id: 'diverse_explorer',
    title: '다양한 탐험가',
    description: '하루에 10개 다른 프로젝트를 조회했습니다',
    icon: '🎪',
    category: 'special',
    rarity: 'epic',
    max: 10,
    tier: 5,
  },
]

// 카테고리별 업적 수
export const ACHIEVEMENT_COUNTS = {
  total: ALL_ACHIEVEMENTS.length,
  exploration: ALL_ACHIEVEMENTS.filter((a) => a.category === 'exploration').length,
  engagement: ALL_ACHIEVEMENTS.filter((a) => a.category === 'engagement').length,
  social: ALL_ACHIEVEMENTS.filter((a) => a.category === 'social').length,
  milestone: ALL_ACHIEVEMENTS.filter((a) => a.category === 'milestone').length,
  level: ALL_ACHIEVEMENTS.filter((a) => a.category === 'level').length,
  xp: ALL_ACHIEVEMENTS.filter((a) => a.category === 'xp').length,
  quest: ALL_ACHIEVEMENTS.filter((a) => a.category === 'quest').length,
  special: ALL_ACHIEVEMENTS.filter((a) => a.category === 'special').length,
}

// 희귀도별 업적 수
export const RARITY_COUNTS = {
  common: ALL_ACHIEVEMENTS.filter((a) => a.rarity === 'common').length,
  rare: ALL_ACHIEVEMENTS.filter((a) => a.rarity === 'rare').length,
  epic: ALL_ACHIEVEMENTS.filter((a) => a.rarity === 'epic').length,
  legendary: ALL_ACHIEVEMENTS.filter((a) => a.rarity === 'legendary').length,
  mythic: ALL_ACHIEVEMENTS.filter((a) => a.rarity === 'mythic').length,
}
